Feature: User can edit the information of an existing video

#   Scenario: user can edit the URL of an existing video
#      Given ...
#      When  ...
#      Then  ...
#
#    Scenario: user can edit the title of an existing video
#       Given ...
#       When  ...
#       Then  ...
#
#    Scenario: user cannot set the URL of a video to empty
#       Given ...
#       When  ...
#       Then  ...
#
#    Scenario: user can set the title of a video to empty
#       Given ...
#       When  ...
#       Then  ...
#
#    Scenario: user cannot edit the URL of a video to be the same as another existing video URL
#       Given ...
#       When  ...
#       Then  ...
