Feature: User can edit the information of an existing book

   Scenario: user can edit the title of an existing book
      Given book with title "Kirja123456", author "Kirjailija123456" and ISBN "00-000-00" has been added
      And   command "edit book" is selected
      When  command "1" is selected
      And   title "Kirja789" is entered
      And   author "Kirjailija789" is entered
      And   ISBN "11-111-11" is entered
      And   command "browse" is selected
      Then  book with title "Kirja789" and author "Kirjailija789" and ISBN "11-111-11" is printed

#    Scenario: user can edit the author of an existing book
#       Given ...
#       When  ...
#       Then  ...
#
#    Scenario: user cannot set the title of a book to empty
#       Given ...
#       When  ...
#       Then  ...
#
#    Scenario: user cannot set the author of a book to empty
#       Given ...
#       When  ...
#       Then  ...
#
#    Scenario: user can set the ISBN of a book to empty
#       Given ...
#       When  ...
#       Then  ...
#
#    Scenario: user cannot edit the title and author of a book to be the same as another existing book title and author
#       Given ...
#       When  ...
#       Then  ...