Feature: User can edit the information of an existing video

   Scenario: user can edit the URL and title of an existing video
      Given video with URL "www.jees.com" and name "Jees video" has been added 
      And 	command "edit video" is selected
      When  command "1" is selected
      And   title "New title" is entered
      And   URL "New URL" is entered
      And   command "browse" is selected
      Then  video with title "New title" and URL "New URL" is printed

#    Scenario: user cannot set the URL of a video to empty
#       Given ...
#       When  ...
#       Then  ...
#
#    Scenario: user can set the title of a video to empty
#       Given ...
#       When  ...
#       Then  ...
#
#    Scenario: user cannot edit the URL of a video to be the same as another existing video URL
#       Given ...
#       When  ...
#       Then  ...
